CREATE TABLE smmh_data (
	Age DECIMAL,
	Gender VARCHAR(20),
	RelationshipStatus VARCHAR(50),
	Occupation VARCHAR(30),
	Organization VARCHAR(30),
	SocialMedia BOOLEAN,
	SocialMediaPlatforms VARCHAR(255),
	NumberofSocialMediaPlatforms INT,
	HoursSpent VARCHAR(30),
	Frequency INT,
	Distraction INT,
	Restlessness INT,
	Anxiety	INT,
	ConcentrationDifficulty	INT,
	SelfComparision	INT,
	PostSentiment INT,
	ValidationSeeking INT,
	Depression INT,
	ActivityInterest INT,
	Sleeplessness INT,
	Reddit INT,
	YouTube INT,
	Snapchat INT,
	Pinterest INT,
	TikTok INT,
	Instagram INT,
	Discord INT,
	Facebook INT,
	Twitter INT,
	two_to_five_hrs INT,
	less_than_two_hrs INT,
	more_than_five_hrs INT);
	
DELETE TABLE smmh_data;